- hosts: rke2_cluster
  name: Destroy RKE2 Cluster
  gather_facts: false
  tasks:
    - name: Prepare Hosts
      when:
        - ansible_os_family == 'Debian'
        - inventory_hostname in groups["rke2_cluster"]
      tags:
        - destroy-cluster
      block:
        - pause:
            prompt: "Be aware of what you're doing. **THIS CLUSTER WILL BE DESTROYED**"

        - pause:
            seconds: 3
      
        - name: Destroy RKE2
          shell: '/usr/local/bin/rke2-uninstall.sh'
          register: output
          ignore_errors: true
          no_log: true

        - debug:
            msg: "{{ output.stderr }}"
          when: output.failed == true

        - name: Purge files
          file:
            path: "/root/.kube"
            state: absent

        - file:
            path: /etc/logrotate.d/rke2
            state: absent
